const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const Sync=require('../src/sync-core.js');
function setup(){
 let local={tracked:['running']},meta=null,remote={revision:0,state:null},fail=false,backups=[],replies=[];
 const options={load:()=>structuredClone(local),replace:s=>{local=structuredClone(s);},readMeta:()=>meta,writeMeta:m=>{meta=structuredClone(m);},backup:s=>backups.push(s),status:s=>replies.push(s),api:async(method,s,rev)=>{
  if(fail)throw Error('offline');if(method==='GET')return structuredClone(remote);
  if(rev!==remote.revision)throw Object.assign(Error('Conflict'),{status:409,remote:structuredClone(remote)});
  remote={revision:rev+1,state:structuredClone(s)};return structuredClone(remote);
 }};
 let core=new Sync(options);
 return {get core(){return core;},options,change:s=>{local=s;},remote:s=>{remote=s;},offline:v=>{fail=v;},restart:()=>{core=new Sync(options);},local:()=>local,server:()=>remote,replies,backups};
}
test('offline edits survive reload and sync on reconnect',async()=>{const s=setup();s.change({tracked:['running','guitar']});s.offline(true);await s.core.sync();assert.equal(s.core.status,'offline');s.restart();assert.ok(s.core.dirty());s.offline(false);await s.core.sync();assert.deepEqual(s.server().state,s.local());assert.equal(s.core.status,'synced');});
test('new device downloads cloud progress without overwriting it',async()=>{const s=setup();s.remote({revision:3,state:{tracked:['chess']}});await s.core.sync();assert.deepEqual(s.local().tracked,['chess']);assert.equal(s.server().revision,3);});
test('simultaneous offline and cloud edits require explicit resolution',async()=>{const s=setup();s.change({tracked:['guitar']});s.remote({revision:2,state:{tracked:['chess']}});await s.core.sync();assert.equal(s.core.status,'conflict');assert.deepEqual(s.local().tracked,['guitar']);assert.deepEqual(s.server().state.tracked,['chess']);await s.core.resolve('device');assert.deepEqual(s.server().state.tracked,['guitar']);assert.equal(s.backups.length,1);});
test('use-cloud saves a local backup before replacing hobbies',async()=>{const s=setup();s.change({tracked:['guitar']});s.remote({revision:2,state:{tracked:['chess']}});await s.core.sync();await s.core.resolve('cloud');assert.deepEqual(s.local().tracked,['chess']);assert.deepEqual(s.backups[0].tracked,['guitar']);});
test('lost success reply recognizes identical server state on retry',async()=>{const s=setup();s.change({tracked:['guitar']});s.remote({revision:1,state:{tracked:['guitar']}});await s.core.sync();assert.equal(s.core.status,'synced');assert.equal(s.server().revision,1);});
test('changes during upload remain pending, rather than acknowledged early',async()=>{const s=setup();const api=s.options.api;s.options.api=async(...args)=>{const result=await api(...args);if(args[0]==='PUT')s.change({tracked:['guitar','chess']});return result;};s.change({tracked:['guitar']});await s.core.sync();assert.equal(s.core.status,'pending');assert.deepEqual(s.server().state.tracked,['guitar']);});
test('signing out during a request prevents late downloads replacing another account',async()=>{const s=setup();let finish;s.options.api=()=>new Promise(resolve=>finish=resolve);const running=s.core.sync();s.core.stop();s.change({tracked:['other-account']});finish({revision:9,state:{tracked:['private']}});await running;assert.deepEqual(s.local().tracked,['other-account']);});
test('storage failure during conflict backup does not discard device changes',async()=>{const s=setup();s.change({tracked:['guitar']});s.remote({revision:2,state:{tracked:['chess']}});await s.core.sync();s.options.backup=()=>{throw Error('storage full');};assert.throws(()=>s.core.resolve('cloud'));assert.deepEqual(s.local().tracked,['guitar']);});
function engine(){const data=new Map();const c=vm.createContext({console,localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)}});for(const file of ['data.js','engine.js'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../src',file),'utf8'),c);c.SQ.init();return {c,data};}
test('engine isolates account copies and preserves guest hobbies',()=>{const {c}=engine();c.SQ.addHobby('running');c.SQ.useStorage('habitual.account.alice');assert.equal(c.SQ.state.tracked.length,0);c.SQ.addHobby('guitar');c.SQ.useStorage('sidequest.v1');assert.equal(c.SQ.state.tracked[0].hobbyId,'running');c.SQ.useStorage('habitual.account.alice');assert.equal(c.SQ.state.tracked[0].hobbyId,'guitar');});
test('saving still works offline and observers receive storage failures',()=>{const {c}=engine();let result;c.SQ.subscribe(ok=>result=ok);c.SQ.addHobby('running');assert.equal(result,true);c.localStorage.setItem=()=>{throw Error('Quota');};c.SQ.setGoal('running',4);assert.equal(result,false);assert.equal(c.SQ.state.tracked[0].goal,4);});
test('remote attendance uses confirmed server totals and fixed dates',()=>{const {c}=engine();c.SQ.setRemoteEvents([{id:'live',startsAt:'2030-05-01T12:00:00Z',going:10,rsvp:true,spots:20}]);const e=c.SQ.events()[0];assert.equal(e.going,9);assert.equal(e.rsvp,true);assert.equal(e.canCheckIn,false);assert.equal(e.date,'2030-05-01');});
